### ISSUE TITLE
Wreckfest not working

### ISSUE THREAD

**Issue by Macley-Kun** [OpenSourceLAN/gameservers-docker#18]
```
wine: created the configuration directory '/home/steam/.wine'
002c:fixme:winediag:__wine_start_process Wine Staging 5.15 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
0048:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:get_local_server_stream Failed: 80004002
0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0050:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 183
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x800736b7
0050:err:ole:get_local_server_stream Failed: 800736b7
002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0040:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0040:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0058:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0058:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0060:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0060:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not find Wine Gecko. HTML rendering will be disabled.
0094:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0094:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
009c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
009c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not find Wine Gecko. HTML rendering will be disabled.
00bc:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
002c:err:setupapi:SetupDiInstallDevice Failed to start service L"wineusb" for device L"ROOT\\WINE\\WINEUSB", error 1114.
wine: configuration in L"/home/steam/.wine" has been updated.
0024:fixme:file:NtLockFile I/O completion on lock not implemented yet
00d8:fixme:process:CreateProcessInternalW Unsupported attribute 0x20002.
00e0:fixme:process:SetProcessShutdownParameters (00000100, 00000001): partial stub.
00e0:fixme:file:NtLockFile I/O completion on lock not implemented yet
00e4:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00e4:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
[220:228:20200816,095843.123:ERROR session_end_watcher.cc:171] CreateWindow: Success. (0)
0108:fixme:ver:GetCurrentPackageId (0031FE34 00000000): stub
011c:fixme:ver:GetCurrentPackageId (1818FEFC 00000000): stub
Commands:
    list - print player list
    bans - print ban list
    admins - print list of user privileges
    clearusers - clear user privileges
    tracks - list tracks
    gamemodes - list game modes
    cars - list cars
    weathers - list weathers
    exit - close application
    ? - list server and event modifiers
Chat commands:
    /message [new message] - send a message to the chat
    /kick [id] - kick a player
    /ban [id] - ban a player
    /bansteamid [steam id] - ban a steam id
    /unban [ban index] - lift a ban, use "bans" for ban indices
    /unbansteamid [steam id] - lift a ban by steam id
    /clearbans - clear all bans
    /balanceteams - balance teams
    /restart - server restart
    /bot - add a bot
    /op [id] - add moderator privileges
    /opsteamid [steam id] - add moderator privileges by steam id
    /admin [id] - add admin privileges
    /adminsteamid [steam id] - add admin privileges by steam id
    /demote [id] - clear admin and moderator privileges
    /demotesteamid [steam id] - clear admin and moderator privileges by steam id
    /password [new password] - set password
    /servername [new server name] - set name of the server
    /welcome [new welcome message] - set the welcome message
    /eventloop - toggle automatic event rotation if configured
* 09:58:53 Starting server...
0024:fixme:ntdll:EtwEventRegister ({47a9201e-73b0-42ce-9821-7e134361bc6f}, 3F006C40, 3F04C208, 3F04C200) stub.
0024:fixme:ntdll:EtwEventRegister ({58a9201e-73b0-42ce-9821-7e134361bc70}, 3F006C40, 3F04C240, 3F04C238) stub.
0024:fixme:ntdll:EtwEventRegister ({3fa9201e-73b0-43fe-9821-7e145359bc6f}, 3F006C40, 3F04C1D0, 3F04C1C8) stub.
0024:fixme:ntdll:EtwEventRegister ({1432afee-73b0-42ce-9821-7e134361b433}, 3F006C40, 3F04C278, 3F04C270) stub.
0024:fixme:ntdll:EtwEventRegister ({4372afee-73b0-42ce-9821-7e134361b519}, 3F006C40, 3F04C2B0, 3F04C2A8) stub.
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0130:fixme:iphlpapi:NotifyAddrChange (Handle 0x18f001ec, overlapped 0x18f001f0): stub
014c:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
014c:fixme:wbemprox:client_security_SetBlanket 6795E768, 10CD3660, 10, 0, (null), 3, 3, 00000000, 0x00000000
014c:fixme:wbemprox:client_security_Release 6795E768
0088:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0088:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
014c:fixme:wbemprox:enum_class_object_Next timeout not supported
0088:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0088:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0088:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0088:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
* 09:58:54 Server creation failed. Is Steam client running?
process 29: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 3543.
This is normally a bug in some application using the D-Bus library.
process 29: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 3543.
This is normally a bug in some application using the D-Bus library.
0130:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
process 29: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 3543.
This is normally a bug in some application using the D-Bus library.
process 29: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 3543.
This is normally a bug in some application using the D-Bus library.

```
The display issues could be fixed by giving (error 0050):
```
Xvfb :0 -screen 0 1024x768x16 &
```
Am i'm doing something wrong?
I only run `./build.sh wreckfest` and `./start_server.sh wreckfest`

**Comment by sirsquidness** [comment]
Hello! Can you try running the container directly (not with the shell script), for example, `docker run -it --rm --net=host wreckfest` and see if that makes a difference?

After the `Server creation failed` message, can you do `help` in the console still, or is the game server totally crashed?

Is this your first time trying to use wreckfest server? Did it work for you previously

I'll try and reproduce the problem and find a fix in the next few days

It might be that Wreckfest isn't compatible with a newer version of wine, I might need to look at pinning an older wine version

**Comment by Macley-Kun** [comment]
Heya, i tried running the container with the command you gave, but still same problems occure: sudo docker run -it --rm --net=host wreckfestwine: created the configuration directory '/home/steam/.wine'002c:fixme:winediag:__wine_start_process Wine Staging 5.15 is a testing version containing experimental patches.002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.0048:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800040020048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x800040020048:err:ole:get_local_server_stream Failed: 800040020050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.0050:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 1830050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 00050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 140070050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b70050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x800736b70050:err:ole:get_local_server_stream Failed: 800736b70040:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.0040:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.002c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.0058:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.0058:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.0060:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.0060:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.Could not find Wine Gecko. HTML rendering will be disabled.0094:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.0094:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.009c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.009c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.Could not find Wine Gecko. HTML rendering will be disabled.00c4:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142002c:err:setupapi:SetupDiInstallDevice Failed to start service L"wineusb" for device L"ROOT\\WINE\\WINEUSB", error 1114.wine: configuration in L"/home/steam/.wine" has been updated.0024:fixme:file:NtLockFile I/O completion on lock not implemented yet00dc:fixme:process:CreateProcessInternalW Unsupported attribute 0x20002.00e4:fixme:process:SetProcessShutdownParameters (00000100, 00000001): partial stub.00e4:fixme:file:NtLockFile I/O completion on lock not implemented yet00e8:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.00e8:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.[224:232:20200817,114103.850:ERROR session_end_watcher.cc:171] CreateWindow: Success. (0)010c:fixme:ver:GetCurrentPackageId (0031FE34 00000000): stub0120:fixme:ver:GetCurrentPackageId (1818FEFC 00000000): stubCommands:    list - print player list    bans - print ban list    admins - print list of user privileges    clearusers - clear user privileges    tracks - list tracks    gamemodes - list game modes    cars - list cars    weathers - list weathers    exit - close application    ? - list server and event modifiersChat commands:    /message [new message] - send a message to the chat    /kick [id] - kick a player    /ban [id] - ban a player    /bansteamid [steam id] - ban a steam id    /unban [ban index] - lift a ban, use "bans" for ban indices    /unbansteamid [steam id] - lift a ban by steam id    /clearbans - clear all bans    /balanceteams - balance teams    /restart - server restart    /bot - add a bot    /op [id] - add moderator privileges    /opsteamid [steam id] - add moderator privileges by steam id    /admin [id] - add admin privileges    /adminsteamid [steam id] - add admin privileges by steam id    /demote [id] - clear admin and moderator privileges    /demotesteamid [steam id] - clear admin and moderator privileges by steam id    /password [new password] - set password    /servername [new server name] - set name of the server    /welcome [new welcome message] - set the welcome message    /eventloop - toggle automatic event rotation if configured* 11:41:15 Starting server...0024:fixme:ntdll:EtwEventRegister ({47a9201e-73b0-42ce-9821-7e134361bc6f}, 3F006C40, 3F04C208, 3F04C200) stub.0024:fixme:ntdll:EtwEventRegister ({58a9201e-73b0-42ce-9821-7e134361bc70}, 3F006C40, 3F04C240, 3F04C238) stub.0024:fixme:ntdll:EtwEventRegister ({3fa9201e-73b0-43fe-9821-7e145359bc6f}, 3F006C40, 3F04C1D0, 3F04C1C8) stub.0024:fixme:ntdll:EtwEventRegister ({1432afee-73b0-42ce-9821-7e134361b433}, 3F006C40, 3F04C278, 3F04C270) stub.0024:fixme:ntdll:EtwEventRegister ({4372afee-73b0-42ce-9821-7e134361b519}, 3F006C40, 3F04C2B0, 3F04C2A8) stub.0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.0134:fixme:iphlpapi:NotifyAddrChange (Handle 0x18f001ec, overlapped 0x18f001f0): stub0150:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags0150:fixme:wbemprox:client_security_SetBlanket 6795E768, 10CEB378, 10, 0, (null), 3, 3, 00000000, 0x000000000150:fixme:wbemprox:client_security_Release 6795E7680088:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled0088:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled0150:fixme:wbemprox:enum_class_object_Next timeout not supported0088:fixme:mountmgr:query_property Faking StorageDeviceProperty data0088:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled0088:fixme:mountmgr:query_property Faking StorageDeviceProperty data0088:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled* 11:41:15 Server creation failed. Is Steam client running?process 29: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 3543.This is normally a bug in some application using the D-Bus library.process 29: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 3543.This is normally a bug in some application using the D-Bus library.0134:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send bufferingprocess 29: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 3543.This is normally a bug in some application using the D-Bus library.process 29: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 3543.This is normally a bug in some application using the D-Bus library. I can indeed type help and get the commands that are available back.This is the first time ever working with any steamcmd game server for me. I used docker as i believed it’s just pull run and go. I’m using Ubuntu 20.04 LTS if that might help. I did try running it also outside of docker, and i managed to run it withoud any errors or warnings, aside of the steam one. But i don’t believe people from the internet can access that server if steam isn’t able to create the server right? Van: Chris HVerzonden: maandag 17 augustus 2020 10:56Aan: OpenSourceLAN/gameservers-dockerCC: Macley; AuthorOnderwerp: Re: [OpenSourceLAN/gameservers-docker] Wreckfest not working (#18) Hello! Can you try running the container directly (not with the shell script), for example, docker run -it --rm --net=host wreckfest and see if that makes a difference?After the Server creation failed message, can you do help in the console still, or is the game server totally crashed?Is this your first time trying to use wreckfest server? Did it work for you previouslyI'll try and reproduce the problem and find a fix in the next few daysIt might be that Wreckfest isn't compatible with a newer version of wine, I might need to look at pinning an older wine version—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fritogotlayed** [comment]
I can confirm that I'm having trouble getting wreckfest to launch as well. It doesn't appear to matter if I'm running via the helper `.sh` scripts or if I run directly via the docker command. Every thing that I have tried debugging wise has not helped. I tried some poking around last night too see about debugging and one thing I noticed is during the build it appears to use "FROM base" instead of [FROM wine](https://github.com/OpenSourceLAN/gameservers-docker/blob/master/wreckfest/Dockerfile#L1) when building the container. Could this be at play here? I suspect it's because [WINE is no longer a base image on docker hub](https://hub.docker.com/_/wine/).

For completeness here are the runs I have tried: 

* `./start_server.sh wreckfest`
* `docker run -it --rm --net=host wreckfest`
* `docker run -it --rm --net=host -v /home/my-user/git-source/gameservers-docker/wreckfest/server_config.cfg:/steam/wreckfest/server_config.cfg wreckfest wine Wreckfest.exe -s server_config=server_config.cf`
    * with this one I had updated the config to run on lan and wanted to bypass the config cat just to be sure

**Comment by Macley-Kun** [comment]
Mmm I see, I didn’t notice that!
Would this image be useful? https://hub.docker.com/r/scottyhardy/docker-wine/

Met vriendelijke groet,

Wesley de Vree
________________________________
Van: Frito <notifications@github.com>
Verzonden: Wednesday, August 26, 2020 11:27:06 PM
Aan: OpenSourceLAN/gameservers-docker <gameservers-docker@noreply.github.com>
CC: Macley <wesley.de.vree@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [OpenSourceLAN/gameservers-docker] Wreckfest not working (#18)


I can confirm that I'm having trouble getting wreckfest to launch as well. It doesn't appear to matter if I'm running via the helper .sh scripts or if I run directly via the docker command. Every thing that I have tried debugging wise has not helped. I tried some poking around last night too see about debugging and one thing I noticed is during the build it appears to use "FROM base" instead of FROM wine<https://github.com/OpenSourceLAN/gameservers-docker/blob/master/wreckfest/Dockerfile#L1> when building the container. Could this be at play here? I suspect it's because WINE is no longer a base image on docker hub<https://hub.docker.com/_/wine/>.

For completeness here are the runs I have tried:

  *   ./start_server.sh wreckfest
  *   docker run -it --rm --net=host wreckfest
  *   docker run -it --rm --net=host -v /home/my-user/git-source/gameservers-docker/wreckfest/server_config.cfg:/steam/wreckfest/server_config.cfg wreckfest wine Wreckfest.exe -s server_config=server_config.cf
     *   with this one I had updated the config to run on lan and wanted to bypass the config cat just to be sure

**Comment by sirsquidness** [comment]
Hello again! Quick update...

I was able to reproduce your issue, but so far no luck in a fix.

I had a 12 month old version of the container about. Starting that I could confirm that (outdated) Wreckfest worked (although outdated so I could see it but not join the game). I updated the game inside that container, and it no longer works. No other changes - same wine version, same OS, libraries, etc.

This suggests that there has been a change in Wreckfest that either is no longer compatible with WINE, or there are dependencies that have changed which need to be added.

It might not be fixable.

Re: the `FROM wine` suggestion.. the wine image being referenced is built from the `wine/` folder in this repo.

**Comment by Macley-Kun** [comment]
I was afraid that would be the case, i suggest if your ok with it, to remove the wreckfest support and to close the issue then.
Seems that the game is only runnable on pure windows servers, thank you for all your time however!

**Comment by gOOvER** [comment]
Old Error, but here is the solution (because i found this on google)

add:
`+@sSteamCmdForcePlatformType windows`

when you download it via steamcmd

**Comment by Macleykun** [comment]
To the command line? Perhaps it's handier to make a pull so every user can use this fix aswell :) (in the readme/script)
and thanks for finding this issue!

**Comment by gOOvER** [comment]
> To the command line? Perhaps it's handier to make a pull so every user can use this fix aswell :) (in the readme/script) and thanks for finding this issue!

yes to cmd line:

as example
`./steamcmd.sh +@sSteamCmdForcePlatformType windows +login anonymous +force_install_dir ../csgo_ds +app_update 740 validate +quit`
