### ISSUE TITLE
Issue - Wreckfest installation

### ISSUE THREAD

**Issue by kimizumi1** [OpenSourceLAN/gameservers-docker#19]
Hello!

Installing Wreckfest gives a ton of errors:
Package iproute2 is not available
Package unzip is not available
Package lib32gcc1 is not available
and
pull access denied for base, repository does not exist or may require 'docker login'
pull access denied for steamcmd, repository does not exist or may require 'docker login'
pull access denied for wine, repository does not exist or may require 'docker login'

OS: Azure Ubuntu image version 18.04

**Comment by sirsquidness** [comment]
Hi,

It builds on the other images available in this repo. They aren't pushed to docker hub as they are too large and too frequently changing to be worth it so you need to build them yourself. The included build.sh script should sort out the build order


That said, wreckfest appears to have broken with a recent update. The game doesn't seem to work in wine anymore.

**Comment by propstg** [comment]
> That said, wreckfest appears to have broken with a recent update. The game doesn't seem to work in wine anymore.

After that update, I had to change `wreckfest/start-wreckfest.sh` to use `server/Wreckfest.exe` to get past the "Server creation failed. Is Steam client running?" error. (My fork has unrelated and outdated changes, because I'm a monster, or I'd submit a PR)

```
exec wine Wreckfest.exe -s server_config=server_config.cfg
```
to
```
exec wine server/Wreckfest.exe -s server_config=server_config.cfg
```

**Comment by DanielLeushuis** [comment]
Hi,

I have the same issue as you have @propstg. I did try your change but without any luck. Still the same error: 

`Server creation failed. Is Steam client running?`

Any chance to get Wreckfest running on Linux through this docker?

**Comment by propstg** [comment]
Hmm, is your Wreckfest server up to date, @DanielLeushuis? If so, I'm not sure what else it might be.

I'm running it on a Linode instance and it works with server/Wreckfest.exe and fails with Wreckfest.exe, for me. The same change did help someone get their Wreckfest server working in wine again, when I suggested the change to them on the Wreckfest discord server.

```
gregory@li1320-177:~$ sudo cat /var/lib/docker/overlay2/c9c7552d797bba831d775b9cd9c109f85cc599288254b7623c6e793e380b9020/merged/steam/wreckfest/start-wreckfest.sh | grep Wreckfest.exe
exec wine server/Wreckfest.exe -s server_config=/steam/config/server_config.cfg

gregory@li1320-177:~$ sudo docker start wreckfest
wreckfest

gregory@li1320-177:~$ sudo docker logs --tail 1 wreckfest
* 01:34:47 Server connected to Steam.

gregory@li1320-177:~# sudo vim /var/lib/docker/overlay2/c9c7552d797bba831d775b9cd9c109f85cc599288254b7623c6e793e380b9020/merged/steam/wreckfest/start-wreckfest.sh

gregory@li1320-177:~$ sudo cat /var/lib/docker/overlay2/c9c7552d797bba831d775b9cd9c109f85cc599288254b7623c6e793e380b9020/merged/steam/wreckfest/start-wreckfest.sh | grep Wreckfest.exe
exec wine Wreckfest.exe -s server_config=/steam/config/server_config.cfg

gregory@li1320-177:~$ sudo docker restart wreckfest
wreckfest

gregory@li1320-177:~$ sudo docker logs wreckfest | grep "Server creation failed" | tail -1
* 01:38:43 Server creation failed. Is Steam client running?
```

**Comment by DanielLeushuis** [comment]
@propstg Thanks for responding. Yeah I did a clean install together with a clean SteamCMD, it is up to date. But in the logs you are showing it fails for you aswell right?

**Comment by propstg** [comment]
@DanielLeushuis Ah, yeah. I guess I've never used `./start_server.sh`, only `docker start wreckfest` (but fwiw, it did work with ./start_server.sh when I tried it right now).

I do have some other changes on my fork that I *thought* were unrelated. I'll try with a clean copy of this repo on a fresh Linode and see if anything else needs to be done in addition to adding `server/`.

**Comment by sirsquidness** [comment]
I've just merged @propstg 's PR #20 , which as far as I can tell fixes the problem ... I can see the server in the Steam LAN server browser again, but since I'm booted in to linux right now I can't test joining from the wreckfest game client. 

@kimizumi1 @DanielLeushuis can you confirm if you were able to get it working after this PR was merged?

**Comment by DanielLeushuis** [comment]
Sorry for my late response. The docker logs do show "Server connected to Steam." now! I can't validate it myself because I don't have the game but I will ask someone to check it out.

**Comment by sirsquidness** [comment]
Hello friends, I've reverted the change made in PR #20 that fixed this problem, as Wreckfest dedicated server no longer has a `server/Wreckfest.exe` binary - #26 for more info. I tested locally and I don't see the symptoms reported in this thread, so :crossed_fingers: fingers crossed this issue won't come back.

It's been most of a year, so I'm going to close this issue... but... if it does come back, please re-open and let me know! :)
