### ISSUE TITLE
metamodsource URL changed

### ISSUE THREAD

**Issue by TheHades** [OpenSourceLAN/gameservers-docker#2]
Hi,

the old "http://www.metamodsource.net/downloads/" doesn't work anymore.

New URL -> http://www.metamodsource.net/downloads.php

Regards,

**Comment by sirsquidness** [comment]
@TheHades - sorry, I thought I replied to this issue back when you raised it. Apparently I didn't! :grimacing: 

@mtdoyle submitted a PR to fix this, so check out latest master and see if this fixes your issue. :+1:
