### ISSUE TITLE
Request: Web Manager

### ISSUE THREAD

**Issue by Protektor-Desura** [OpenSourceLAN/gameservers-docker#30]
It would be nice if there was a web interface for the docker so you could pick which game servers you wanted to run and they just were downloaded installed and configured automatically. So they basically just work then you could edit the configs if needed to customize them.

**Comment by sirsquidness** [comment]
Hi @Protektor-Desura ! thanks for the suggestion

There's definitely going to be web interfaces for docker already that satisfy your needs in this respect. Have a look through results on google for something like "docker web interfaces" or "docker templates" or such. They might not have game servers in the name, but there will definitely be some that have the workflow you describe 👍
