### ISSUE TITLE
Left for dead

### ISSUE THREAD

**Issue by TimPerry** [OpenSourceLAN/gameservers-docker#4]
Found this awesome project, looks great but wondering how difficult it is to add left4dead?

Cheers!

**Comment by sirsquidness** [comment]
Pretty straight forward to do it :)

What are the configuration options you'd want to have available? Give me some example commandd line options and/or config files and I'll throw something together for you 

I do LANs, where L4D servers are pretty useless, so I haven't had a reason to run them in quite some years.

**Comment by TimPerry** [comment]
Sorry, opened this on lunch at work and totally forgot! I think I agree with you now, no need for L4D server. Cheers!
